server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: otp-service
          uri: lb://otp-service
          predicates:
            - Path=/otp/**
        - id: irctc-seat
          uri: lb://irctc-seat
          predicates:
            - Path=/seat/**


        - id: aadhaar-service
          uri: lb://aadhaar-service
          predicates:
            - Path=/aadhaar/**

        - id: mobile-service
          uri: lb://mobile-service
          predicates:
            - Path=/mobile/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
